const labelsContainer = {
  tso: 'TSO',
  clientNumber: 'NUMERO DO CLIENTE',
  dateUser: 'DATA',
  rg: 'RG',
  org_exp: 'ORG EXP',
  cpf: 'CPF',
  date_of_birth: 'DATA DE NASCIMENTO',
  address: 'ENDEREÇO',
  neighborhood: 'BAIRRO',
  city: 'CIDADE',
  uf: 'UF',
  cep: 'CEP',
  phone: 'TELEFONE',
  reference: 'REFERENCIAL',
  cell_phone: 'TELEFONE CELULAR',
  qt1: 'QUANTIDADE I',
  qt2: 'QUANTIDADE II',
  qt3: 'QUANTIDADE III',
  desc1: 'DESCRIÇÃO LENTES/ARMAÇÃO I',
  desc2: 'DESCRIÇÃO LENTES/ARMAÇÃO II',
  desc3: 'DESCRIÇÃO LENTES/ARMAÇÃO III',
  price1: 'VALOR I',
  price2: 'VALOR II',
  price3: 'VALOR III',
  grau_esferico_od: 'GRAU ESFÉRICO OD',
  cilindrico_od: 'CILINDRICO OD',
  eixo_od: 'EIXO OD',
  dpn_od: 'DPN OD',
  ap_od: 'AP OD',
  cilindrico_oe: 'CILINDRICO OE',
  eixo_oe: 'EIXO OE',
  dpn_oe: 'DPN OE',
  ap_oe: 'AP OE',
  name: 'NOME',
  father: 'PAI',
  mother: 'MAE',
  grau_esferico_oe: 'GRAU ESFÉRICO OE',
  grau_esferico_od_perto: 'GRAU ESFERICO OD PERTO',
  cilindrico_od_perto: 'CILINDRICO OD PERTO',
  eixo_od_perto: 'EIXO OD PERTO',
  dpn_od_perto: 'DPN OD PERTO',
  ap_od_perto: 'AP OD PERTO',
  grau_esferico_oe_perto: 'GRAU ESFERICO OE PERTO',
  cilindrico_oe_perto: 'CILINDRICO OE PERTO',
  eixo_oe_perto: 'EIXO OE PERTO',
  dpn_oe_perto: 'DPN OE PERTO',
  ap_oe_perto: 'AP OE PERTO',
};

export default labelsContainer;
